server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #create(drop table if exists tbl1 => 기존 테이블 데이터 사라질 수 있음), update, none, 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity(테이블) 생성 시 변수명 그대로 필드명 설정하는 기능
      # use-new-id-generator-mappings : JPA가 사용하는 기본 넘버링 전략을 따라갈 것인가?
      use-new-id-generator-mappings: false # @GeneratedValue(strategy = GenerationType.IDENTITY) 연결된 DB 넘버링 전략 따라갈 것이다.
    #show-sql: true # 콘솔창에 sql문 보여주는 기능
    properties:
      hibernate.format_sql: true # 한 줄이 아닌 한 줄 띄어쓰기 되어 콘솔창에 보여줌

  jackson:
    serialization:
      fail-on-empty-beans: false